# Generated by Django 4.2.23 on 2025-08-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("taxi", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="manufacturer", options={"ordering": ("name",)}
        )
    ]
