# Generated by Django 4.2.23 on 2025-08-08 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("taxi", "0002_alter_manufacturer_options")]

    operations = [
        migrations.RemoveField(model_name="car", name="driver"),
        migrations.AlterField(
            model_name="driver",
            name="license_number",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name="car",
            name="driver",
            field=models.ManyToManyField(
                related_name="cars", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
