# Generated by Django 4.2.23 on 2025-08-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_remove_car_driver_alter_driver_license_number_and_more")
    ]

    operations = [
        migrations.AlterModelOptions(name="driver", options={"ordering": ("username",)})
    ]
